package csv;

public class SourceCode {
	public int change_ID;
	public int ADDING_ATTRIBUTE_MODIFIABILITY;
	public int ADDING_CLASS_DERIVABILITY;
	public int ADDING_METHOD_OVERRIDABILITY;
	public int ADDITIONAL_CLASS;
	public int ADDITIONAL_FUNCTIONALITY;
	public int ADDITIONAL_OBJECT_STATE;
	public int ALTERNATIVE_PART_DELETE;
	public int ALTERNATIVE_PART_INSERT;
	public int ATTRIBUTE_RENAMING; // newEntity
	public int ATTRIBUTE_TYPE_CHANGE; // root
	public int CLASS_RENAMING; // rootEntity
	public int COMMENT_DELETE;
	public int COMMENT_INSERT;
	public int COMMENT_MOVE;
	public int COMMENT_UPDATE;
	public int CONDITION_EXPRESSION_CHANGE;
	public int DECREASING_ACCESSIBILITY_CHANGE; // changedEntity
	public int DOC_DELETE;
	public int DOC_INSERT;
	public int DOC_UPDATE;
	public int INCREASING_ACCESSIBILITY_CHANGE;
	public int METHOD_RENAMING; // newEntity
	public int PARAMETER_DELETE; // root
	public int PARAMETER_INSERT; // root
	public int PARAMETER_ORDERING_CHANGE; // root
	public int PARAMETER_RENAMING;
	public int PARAMETER_TYPE_CHANGE; // root
	public int PARENT_CLASS_CHANGE;
	public int PARENT_CLASS_DELETE;
	public int PARENT_CLASS_INSERT;
	public int PARENT_INTERFACE_CHANGE;
	public int PARENT_INTERFACE_DELETE;
	public int PARENT_INTERFACE_INSERT;
	public int REMOVED_CLASS; // changedEntity
	public int REMOVED_FUNCTIONALITY; // changedEntity
	public int REMOVED_OBJECT_STATE; // changedEntity
	public int REMOVING_ATTRIBUTE_MODIFIABILITY; // root
	public int REMOVING_CLASS_DERIVABILITY;
	public int REMOVING_METHOD_OVERRIDABILITY;
	public int RETURN_TYPE_CHANGE; // root
	public int RETURN_TYPE_DELETE; // root
	public int RETURN_TYPE_INSERT; // root
	public int STATEMENT_DELETE;
	public int STATEMENT_INSERT;
	public int STATEMENT_ORDERING_CHANGE;
	public int STATEMENT_PARENT_CHANGE;
	public int STATEMENT_UPDATE;
	public int UNCLASSIFIED_CHANGE;
	
	public SourceCode(int change_ID) {
		this.change_ID = change_ID;
		ADDING_ATTRIBUTE_MODIFIABILITY = 0;
		ADDING_CLASS_DERIVABILITY = 0;
		ADDING_METHOD_OVERRIDABILITY = 0;
		ADDITIONAL_CLASS = 0;
		ADDITIONAL_FUNCTIONALITY = 0;
		ADDITIONAL_OBJECT_STATE = 0;
		ALTERNATIVE_PART_DELETE = 0;
		ALTERNATIVE_PART_INSERT = 0;
		ATTRIBUTE_RENAMING = 0; // newEntity
		ATTRIBUTE_TYPE_CHANGE = 0; // root
		CLASS_RENAMING = 0; // rootEntity
		COMMENT_DELETE = 0;
		COMMENT_INSERT = 0;
		COMMENT_MOVE = 0;
		COMMENT_UPDATE = 0;
		CONDITION_EXPRESSION_CHANGE = 0;
		DECREASING_ACCESSIBILITY_CHANGE = 0; // changedEntity
		DOC_DELETE = 0;
		DOC_INSERT = 0;
		DOC_UPDATE = 0;
		INCREASING_ACCESSIBILITY_CHANGE = 0;
		METHOD_RENAMING = 0; // newEntity
		PARAMETER_DELETE = 0; // root
		PARAMETER_INSERT = 0; // root
		PARAMETER_ORDERING_CHANGE = 0; // root
		PARAMETER_RENAMING = 0;
		PARAMETER_TYPE_CHANGE = 0; // root
		PARENT_CLASS_CHANGE = 0;
		PARENT_CLASS_DELETE = 0;
		PARENT_CLASS_INSERT = 0;
		PARENT_INTERFACE_CHANGE = 0;
		PARENT_INTERFACE_DELETE = 0;
		PARENT_INTERFACE_INSERT = 0;
		REMOVED_CLASS = 0; // changedEntity
		REMOVED_FUNCTIONALITY = 0; // changedEntity
		REMOVED_OBJECT_STATE = 0; // changedEntity
		REMOVING_ATTRIBUTE_MODIFIABILITY = 0; // root
		REMOVING_CLASS_DERIVABILITY = 0;
		REMOVING_METHOD_OVERRIDABILITY = 0;
		RETURN_TYPE_CHANGE = 0; // root
		RETURN_TYPE_DELETE = 0; // root
		RETURN_TYPE_INSERT = 0; // root
		STATEMENT_DELETE = 0;
		STATEMENT_INSERT = 0;
		STATEMENT_ORDERING_CHANGE = 0;
		STATEMENT_PARENT_CHANGE = 0;
		STATEMENT_UPDATE = 0;
		UNCLASSIFIED_CHANGE = 0;
	}
}
